// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.BuildPilesView = (function(_super) {
    __extends(BuildPilesView, _super);

    function BuildPilesView() {
      _ref = BuildPilesView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    BuildPilesView.prototype.className = 'build-piles';

    BuildPilesView.prototype.template = _.template('\
  <div class="card build-pile"></div>\
  <div class="card build-pile"></div>\
  <div class="card build-pile"></div>\
  <div class="card build-pile"></div>\
  ');

    BuildPilesView.prototype.initialize = function() {
      return this.render();
    };

    BuildPilesView.prototype.render = function() {
      this.$el.children().detach();
      this.$el.html(this.template(this.collection.models));
      return console.log(this.collection);
    };

    return BuildPilesView;

  })(Backbone.View);

}).call(this);
