// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ColumnView = (function(_super) {
    __extends(ColumnView, _super);

    function ColumnView() {
      _ref = ColumnView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ColumnView.prototype.className = 'game-board-column';

    ColumnView.prototype.tagName = 'ul';

    ColumnView.prototype.template = _.template('<p>Column</p>');

    ColumnView.prototype.initialize = function() {
      return this.render();
    };

    ColumnView.prototype.render = function() {
      this.$el.children().detach();
      this.$el.html(this.template(this.collection));
      return this.$el.append(this.collection.map(function(card) {
        return new CardView({
          model: card
        }).$el;
      }));
    };

    return ColumnView;

  })(Backbone.View);

}).call(this);
