// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.GameView = (function(_super) {
    __extends(GameView, _super);

    function GameView() {
      _ref = GameView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    GameView.prototype.template = _.template('\
    <h1>Backbone Solitaire</h1>\
    <div class="piles-container"></div>\
    <div class="build-piles-container"></div>\
    <div class="game-board-container"></div>\
  ');

    GameView.prototype.initialize = function() {
      return this.render();
    };

    GameView.prototype.render = function() {
      this.$el.children().detach();
      this.$el.html(this.template());
      this.$el.addClass('game-container');
      this.$('.game-board-container').html(new GameBoardView({
        collection: this.model.get('gameBoard')
      }).el);
      return this.$('.piles-container').html(new PileView({
        collection: this.model.get('gamePile')
      }).el);
    };

    return GameView;

  })(Backbone.View);

}).call(this);
