// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.PileView = (function(_super) {
    __extends(PileView, _super);

    function PileView() {
      _ref = PileView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PileView.prototype.className = 'pile';

    PileView.prototype.template = _.template('\
  <h2>Deck</h2>\
  <div class="card covered deck-pile"></div>\
  <div class="card discard-pile"></div>\
  ');

    PileView.prototype.initialize = function() {
      return this.render();
    };

    PileView.prototype.render = function() {
      this.$el.children().detach();
      this.$el.html(this.template(this.collection.models));
      return console.log(this.collection);
    };

    return PileView;

  })(Backbone.View);

}).call(this);
