// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Window.BoardColumn = (function(_super) {
    __extends(BoardColumn, _super);

    function BoardColumn() {
      _ref = BoardColumn.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    BoardColumn.prototype.model = Card;

    BoardColumn.prototype.initialize = function(array, deck, columnID) {
      this.deck = deck;
    };

    return BoardColumn;

  })(Backbone.Collection);

}).call(this);
