// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Column = (function(_super) {
    __extends(Column, _super);

    function Column() {
      _ref = Column.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Column.prototype.model = Card;

    Column.prototype.initialize = function(cardArray, deck, columnID) {
      this.deck = deck;
    };

    return Column;

  })(Backbone.Collection);

}).call(this);
