// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.GameBoard = (function(_super) {
    __extends(GameBoard, _super);

    function GameBoard() {
      _ref = GameBoard.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    GameBoard.prototype.model = Card;

    GameBoard.prototype.initialize = function(columnArray, deck) {
      this.deck = deck;
    };

    return GameBoard;

  })(Backbone.Collection);

}).call(this);
